# -*- coding: utf-8 -*-
"""Theater Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mU0ak68RiG7Yk4MkMD8kB7vA3Wu7che
"""

##Theater Python Program --> Program to purchase tickets from the montthly programm

name = input("Type your name to start the program: ")

print("\nHello", name, ", welcome to Theater Python!\n\n")

#variables for performance Options
dance = "Lost in repetition"
theater = "The poetics of surviving"

#Performance selection loop

while True:
  print("Which performance would you would like to purchase?\n")
  print("1. ", dance)
  print("2. ", theater)

  perf_option = input("\nType the option number you would like to purchase: ")

  if perf_option == '1':
    print("\nYou are buying tickets for '", dance, "'")
    break #Exit loop if input is valid

  elif perf_option =='2':
    print("\nYou are buying tickets for '", theater, "'")
    break #Exit loop if input is valid

  else:
    print("\nInvalid option. Try again.\n")

#variable: list of date options
date = ["Fri, 28 March", "Sat, 29 March", "Sun, 30 March"]

#Date selection loop
while True:
  print("\nSelect the date fo your purchase\n")
  print("1. ", date[0])
  print("2. ", date[1])
  print("3. ", date[2])

  date_option = input("\nType the option number you would like to purchase: ")

  if date_option == '1':
    date_option = date[0]
    break #Exit loop if input is valid

  elif date_option == '2':
    date_option = date[1]
    break #Exit loop if input is valid

  elif date_option == '3':
    date_option = date[2]
    break #Exit loop if input is valid

  else:
    print("\nInvalid option. Try again.\n")

ticket = 35.50 #variable of the ticket price

while True:
  qtd = int(input("\nHow many tickets would you like to purchase?: ")) #quantity of tickets
  if qtd <= 5:
    print("\nThe total price is €", (qtd * ticket))
    break #Finish program
  else:
    print("\nInvalid number. You can only buy a maximum of 5 tickets. Try again.")